/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourseallocationsystem.ViewClass;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddHall extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs =null;
    
    
    
    public void clearFields(){
        hallNoText.setText(null);
        capacityText.setText(null);
        dailyChargeText.setText(null);
    }
   

    /**
     * Creates new form AddHall
     */
    public AddHall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hallNoLabel = new javax.swing.JLabel();
        hallNoText = new javax.swing.JTextField();
        capacityLabel = new javax.swing.JLabel();
        capacityText = new javax.swing.JTextField();
        dailyChargeLabel = new javax.swing.JLabel();
        dailyChargeText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Hall");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 33, -1, -1));

        hallNoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hallNoLabel.setText("Hall Number");
        jPanel1.add(hallNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 106, -1, -1));
        jPanel1.add(hallNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 103, 293, -1));

        capacityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        capacityLabel.setText("Hall Capacity(No of people)");
        jPanel1.add(capacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 169, -1, -1));
        jPanel1.add(capacityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 166, 293, -1));

        dailyChargeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dailyChargeLabel.setText("Daily Charge(Rs.)");
        jPanel1.add(dailyChargeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 238, 99, -1));
        jPanel1.add(dailyChargeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 235, 293, -1));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 325, -1, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 137, -1, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 188, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 86, -1, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 235, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Dulanji Rashmika Academic\\First  Year - Sem 2\\ResourseAllocationSystem\\src\\BackgroundImages\\coverpg.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();        
    }//GEN-LAST:event_okButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO hall"
                    +"(hallNo,capacity,dailyCharge)"
                    +"VALUES (?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, hallNoText.getText());
            pat.setString(2,capacityText.getText());
            pat.setString(3,dailyChargeText.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hall Added Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM hall WHERE hallNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, hallNoText.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hall Deleted Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT hallNo, capacity, dailyCharge FROM hall WHERE hallNo = ? ";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, hallNoText.getText());
            ResultSet rs = pat.executeQuery();
            
            if(rs.next() == false)
            {
                JOptionPane.showMessageDialog(this, "Not Found");
                capacityText.setText("");
                dailyChargeText.setText("");
                hallNoText.requestFocus();
            }
            else{
                capacityText.setText(rs.getString("capacity"));
                dailyChargeText.setText(rs.getString("dailyCharge"));
            }
            }
        
        catch(SQLException | HeadlessException ex){
                  JOptionPane.showMessageDialog(null, ex);            
        }                                           
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTextField capacityText;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dailyChargeLabel;
    private javax.swing.JTextField dailyChargeText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hallNoLabel;
    private javax.swing.JTextField hallNoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
