/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourseallocationsystem.ViewClass;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddPayment extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs =null;
        
    public void clearFields(){
        hallNoText.setText(null);
        noOfDaysText.setText(null);
        dailyChargeText.setText(null);
        paymentText.setText(null);
        
    }
   

    /**
     * Creates new form AddPayment
     */
    public AddPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        noOfdaysLabel = new javax.swing.JLabel();
        dailyChargeLabel = new javax.swing.JLabel();
        noOfDaysText = new javax.swing.JTextField();
        dailyChargeText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        okbutton = new javax.swing.JButton();
        calPaymentButton = new javax.swing.JButton();
        paymentText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hallNoLabel = new javax.swing.JLabel();
        hallNoText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        paymentLabel.setText("Payment");
        jPanel1.add(paymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 35, -1, -1));

        noOfdaysLabel.setText("Number of Dates");
        jPanel1.add(noOfdaysLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        dailyChargeLabel.setText("Daily Charge");
        jPanel1.add(dailyChargeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        noOfDaysText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfDaysTextActionPerformed(evt);
            }
        });
        jPanel1.add(noOfDaysText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 194, -1));

        dailyChargeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyChargeTextActionPerformed(evt);
            }
        });
        jPanel1.add(dailyChargeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 194, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 116, -1, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 192, -1, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 270, -1, -1));

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(okbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        calPaymentButton.setText("Calculate Payment");
        calPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calPaymentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(calPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        paymentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTextActionPerformed(evt);
            }
        });
        jPanel1.add(paymentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 194, -1));

        jLabel1.setText("Payment Amount");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        hallNoLabel.setText("Hall Number");
        jPanel1.add(hallNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        hallNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallNoTextActionPerformed(evt);
            }
        });
        jPanel1.add(hallNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 194, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Dulanji Rashmika Academic\\First  Year - Sem 2\\ResourseAllocationSystem\\src\\BackgroundImages\\coverpg.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noOfDaysTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfDaysTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfDaysTextActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();        
    }//GEN-LAST:event_okbuttonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "INSERT INTO payment"
                    +"(hallno,noOfDays,dailyCharge,amount)"
                    +"VALUES (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            
            pat.setString(1,hallNoText.getText());
            pat.setString(2,noOfDaysText.getText());
            pat.setString(3,dailyChargeText.getText());
            pat.setString(4,paymentText.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Payment Added Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM payment WHERE hallno = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, hallNoText.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Payment Deleted Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void calPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calPaymentButtonActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(dailyChargeText.getText());
        int b = Integer.parseInt(noOfDaysText.getText());
        double c = a*b;
        
        paymentText.setText(""+c);
        
    }//GEN-LAST:event_calPaymentButtonActionPerformed

    private void dailyChargeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyChargeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyChargeTextActionPerformed

    private void paymentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTextActionPerformed

    private void hallNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hallNoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    public javax.swing.JButton calPaymentButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dailyChargeLabel;
    private javax.swing.JTextField dailyChargeText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hallNoLabel;
    private javax.swing.JTextField hallNoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField noOfDaysText;
    private javax.swing.JLabel noOfdaysLabel;
    private javax.swing.JButton okbutton;
    private javax.swing.JLabel paymentLabel;
    public javax.swing.JTextField paymentText;
    // End of variables declaration//GEN-END:variables
}
