/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourseallocationsystem.ViewClass;

import java.awt.HeadlessException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class ContinuousPeriod extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pat=null;
    ResultSet rs =null;
    
    public void clearFields(){
        firstDateChooser.setDate(null);
        lastDateChooser.setDate(null);
        noOfDatesText.setText(null);
    }

    /**
     * Creates new form ContinuousPeriod
     */
    public ContinuousPeriod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstDateLabel = new javax.swing.JLabel();
        lastDateLabel = new javax.swing.JLabel();
        firstDateChooser = new com.toedter.calendar.JDateChooser();
        lastDateChooser = new com.toedter.calendar.JDateChooser();
        okButton = new javax.swing.JButton();
        noOfDatesText = new javax.swing.JTextField();
        noOfdatesLabel = new javax.swing.JLabel();
        calDatesButton = new javax.swing.JButton();
        addButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JToggleButton();
        clearButton = new javax.swing.JToggleButton();
        makePaymentButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Continuous Period");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 22, -1, -1));

        firstDateLabel.setText("First Date");
        jPanel1.add(firstDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 86, -1, -1));

        lastDateLabel.setText("Last Date");
        jPanel1.add(lastDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 165, -1, -1));
        jPanel1.add(firstDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 80, 164, -1));
        jPanel1.add(lastDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 159, 164, -1));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 325, -1, -1));

        noOfDatesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfDatesTextActionPerformed(evt);
            }
        });
        jPanel1.add(noOfDatesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 237, 163, -1));

        noOfdatesLabel.setText("Number of Dates");
        jPanel1.add(noOfdatesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 240, -1, -1));

        calDatesButton.setText("Cal Dates");
        calDatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calDatesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(calDatesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 289, -1, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 80, -1, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 206, -1, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 143, -1, -1));

        makePaymentButton.setText("Make Payment");
        makePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePaymentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(makePaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 261, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Dulanji Rashmika Academic\\First  Year - Sem 2\\ResourseAllocationSystem\\src\\BackgroundImages\\coverpg.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();        
    }//GEN-LAST:event_okButtonActionPerformed

    private void calDatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calDatesButtonActionPerformed
        // TODO add your handling code here:
        try{
        SimpleDateFormat sdf = new SimpleDateFormat("MMM d, y", Locale.ENGLISH);
        Date firstDate = firstDateChooser.getDate();
        Date lastDate = lastDateChooser.getDate();
        
        long diffInMillies = Math.abs(lastDate.getTime() - firstDate.getTime());
        long diff = TimeUnit.DAYS.convert(diffInMillies,TimeUnit.MILLISECONDS);
        
        noOfDatesText.setText(String.valueOf(diff+1));
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
                
        
    }//GEN-LAST:event_calDatesButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM continuousperiod WHERE firstDate = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            
            pat.setString(1,((JTextField)firstDateChooser.getDateEditor().getUiComponent()).getText());
            
            
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
                            
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
       try{
            String sql = "INSERT INTO continuousperiod"
                    +"(firstDate,lastDate,noOfDates)"
                    +"VALUES (?,?,?)";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            
            pat.setString(1,((JTextField)firstDateChooser.getDateEditor().getUiComponent()).getText());
            pat.setString(2,((JTextField)lastDateChooser.getDateEditor().getUiComponent()).getText());
            pat.setString(3,noOfDatesText.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, " Added Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
        

    }//GEN-LAST:event_addButtonActionPerformed

    private void noOfDatesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfDatesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfDatesTextActionPerformed

    private void makePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentButtonActionPerformed
        // TODO add your handling code here:
        AddPayment ap = new AddPayment();
        ap.noOfDaysText.setText(noOfDatesText.getText());
        ap.setVisible(true);
        dispose();        
    }//GEN-LAST:event_makePaymentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContinuousPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContinuousPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContinuousPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContinuousPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContinuousPeriod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addButton;
    public javax.swing.JButton calDatesButton;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JToggleButton deleteButton;
    private com.toedter.calendar.JDateChooser firstDateChooser;
    private javax.swing.JLabel firstDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser lastDateChooser;
    private javax.swing.JLabel lastDateLabel;
    private javax.swing.JButton makePaymentButton;
    public javax.swing.JTextField noOfDatesText;
    private javax.swing.JLabel noOfdatesLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
