/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourseallocationsystem.ViewClass;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author User
 */
public class CustomerRegistration extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs=null;
    
    public void clearFields(){
        nicNoText.setText(null);
        nameText.setText(null);
        teleNoText.setText(null);
        addressText.setText(null);
    }
   

    /**
     * Creates new form CustomerRegistration
     */
    public CustomerRegistration() {
        initComponents();
    }
    
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regFormPanel = new javax.swing.JPanel();
        regFormLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nicNoLabel = new javax.swing.JLabel();
        nicNoText = new javax.swing.JTextField();
        teleNoLabel = new javax.swing.JLabel();
        teleNoText = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        okButten = new javax.swing.JButton();
        clearBotten = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regFormPanel.setBackground(new java.awt.Color(255, 204, 204));
        regFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regFormLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        regFormLabel.setText("Customer Registration Form");
        regFormPanel.add(regFormLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 27, -1, -1));

        nameLabel.setText("Name");
        regFormPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 155, -1, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        regFormPanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 152, 247, -1));

        nicNoLabel.setText("NIC Number");
        regFormPanel.add(nicNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 91, -1, -1));

        nicNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicNoTextActionPerformed(evt);
            }
        });
        regFormPanel.add(nicNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 88, 247, -1));

        teleNoLabel.setText("Telephone Number");
        regFormPanel.add(teleNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 219, -1, -1));
        regFormPanel.add(teleNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 216, 247, -1));

        addressLabel.setText("Address");
        regFormPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 283, -1, -1));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        regFormPanel.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 280, 247, -1));

        okButten.setText("OK");
        okButten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtenActionPerformed(evt);
            }
        });
        regFormPanel.add(okButten, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 347, -1, -1));

        clearBotten.setText("Clear");
        clearBotten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBottenActionPerformed(evt);
            }
        });
        regFormPanel.add(clearBotten, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 139, -1, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        regFormPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 191, -1, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        regFormPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 88, -1, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        regFormPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 244, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Dulanji Rashmika Academic\\First  Year - Sem 2\\ResourseAllocationSystem\\src\\BackgroundImages\\coverpg.jpg")); // NOI18N
        regFormPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void nicNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicNoTextActionPerformed

    private void okButtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtenActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();        
    }//GEN-LAST:event_okButtenActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO customer"
                    +"(nicNo,name,telephoneNo,address)"
                    +"VALUES (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, nicNoText.getText());
            pat.setString(2,nameText.getText());
            pat.setString(3,teleNoText.getText());
            pat.setString(4,addressText.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Customer Added Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
        
       
    }//GEN-LAST:event_addButtonActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM customer WHERE nicNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, nicNoText.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Customer Deleted Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearBottenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBottenActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBottenActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT nicNo, name, telephoneNo, address FROM customer WHERE nicNo = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, nicNoText.getText());
            ResultSet rs = pat.executeQuery();
            
            if(rs.next() == false)
            {
                JOptionPane.showMessageDialog(this, "Not Found");
                nameText.setText("");
                teleNoText.setText("");
                addressText.setText("");
                nicNoText.requestFocus();
            }
            else{
                nameText.setText(rs.getString("name"));
                teleNoText.setText(rs.getString("telephoneNo"));
                addressText.setText(rs.getString("address"));
            }
            }
        
        catch(SQLException | HeadlessException ex){
                  JOptionPane.showMessageDialog(null, ex);            
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton clearBotten;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel nicNoLabel;
    private javax.swing.JTextField nicNoText;
    private javax.swing.JButton okButten;
    private javax.swing.JLabel regFormLabel;
    private javax.swing.JPanel regFormPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel teleNoLabel;
    private javax.swing.JTextField teleNoText;
    // End of variables declaration//GEN-END:variables
}
