/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourseallocationsystem.ViewClass;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HallReservation extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs =null;
    
    public void clearFields(){
        customerIdText.setText(null);
        hallNoText.setText(null);
    }

    /**
     * Creates new form HallReservation
     */
    public HallReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hallNoLabel = new javax.swing.JPanel();
        hallReservationLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerIdText = new javax.swing.JTextField();
        hallNoText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        clearText = new javax.swing.JButton();
        addText = new javax.swing.JButton();
        deleteText = new javax.swing.JButton();
        bookingDaysComboBox = new javax.swing.JComboBox<>();
        bookingDaysLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hallNoLabel.setBackground(new java.awt.Color(255, 204, 204));
        hallNoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hallNoLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hallReservationLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hallReservationLabel.setText("Hall Reservation");
        hallNoLabel.add(hallReservationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 21, -1, -1));

        customerIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerIdLabel.setText("Customer ID");
        hallNoLabel.add(customerIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hall Number");
        hallNoLabel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 134, -1, -1));

        customerIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTextActionPerformed(evt);
            }
        });
        hallNoLabel.add(customerIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 78, 198, -1));
        hallNoLabel.add(hallNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 131, 198, -1));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        hallNoLabel.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 277, -1, -1));

        clearText.setText("Clear");
        clearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextActionPerformed(evt);
            }
        });
        hallNoLabel.add(clearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 117, -1, -1));

        addText.setText("Add");
        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        hallNoLabel.add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 66, -1, -1));

        deleteText.setText("Delete");
        deleteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTextActionPerformed(evt);
            }
        });
        hallNoLabel.add(deleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 166, -1, -1));

        bookingDaysComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "continuous period", "special day" }));
        hallNoLabel.add(bookingDaysComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 186, 198, -1));

        bookingDaysLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookingDaysLabel.setText("Booking days");
        hallNoLabel.add(bookingDaysLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 189, -1, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        hallNoLabel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 214, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Dulanji Rashmika Academic\\First  Year - Sem 2\\ResourseAllocationSystem\\src\\BackgroundImages\\coverpg.jpg")); // NOI18N
        hallNoLabel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hallNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hallNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();        
    }//GEN-LAST:event_okButtonActionPerformed

    private void clearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearTextActionPerformed

    private void deleteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTextActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM hallreservation WHERE customerId = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, customerIdText.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hall Reservation Deleted Successfully.");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
    }//GEN-LAST:event_deleteTextActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "INSERT INTO hallreservation"
                    +"(customerId, hallNo)"
                    +"VALUES (?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, customerIdText.getText());
            pat.setString(2,hallNoText.getText());
            pat.executeUpdate();
        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);

            
        }
        
          if(bookingDaysComboBox.getSelectedItem().equals("continuous period")){
            ContinuousPeriod cp = new ContinuousPeriod();
            cp.show();
        }
        if(bookingDaysComboBox.getSelectedItem().equals("special day")){
            SpecialDay sd = new SpecialDay();
            sd.show();
        }
         
  
    }//GEN-LAST:event_addTextActionPerformed

    private void customerIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT customerId,hallNo FROM hallreservation WHERE customerId = ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/resource allocation system","root","");
            pat = con.prepareStatement(sql);
            pat.setString(1, customerIdText.getText());
            ResultSet rs = pat.executeQuery();
            
            if(rs.next() == false)
            {
                JOptionPane.showMessageDialog(this, "Not Found");
                hallNoText.setText("");
                customerIdText.requestFocus();
            }
            else{
                hallNoText.setText(rs.getString("hallNo"));
            }
            }
        
        catch(SQLException | HeadlessException ex){
                  JOptionPane.showMessageDialog(null, ex);            
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HallReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HallReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HallReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HallReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HallReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addText;
    private javax.swing.JComboBox<String> bookingDaysComboBox;
    private javax.swing.JLabel bookingDaysLabel;
    private javax.swing.JButton clearText;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JButton deleteText;
    private javax.swing.JPanel hallNoLabel;
    private javax.swing.JTextField hallNoText;
    private javax.swing.JLabel hallReservationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
